import { StyleSheet } from 'react-native'

export const HomeStyle = (StyleSheet.createstyle = StyleSheet.create({
  PrimaryMenuButton: { right: 30, position: 'absolute', top: 70 },
  homeLayer: {
    width: '100%',
    height: '100%',
  },
  secondaryMenu: {
    width: '80%',
    height: '50%',
    backgroundColor: '#14213D',
    borderWidth: 2,
    borderColor: '#14213D',
    marginLeft: 'auto',
    marginRight: 'auto',
    marginTop: 20,
    borderRadius: 14,
  },
  chronoContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-around',
    flexWrap: 'wrap',
  },
  chronoItem: {
    width: '45%',
    height: '33%',
    borderColor: 'white',
    borderWidth: 1,
    marginBottom: 20,
    marginTop: 20,
    borderRadius: 9,
  },
  chronoInfo: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    width: '80%',
    height: 100,
    marginTop: 100,
    marginLeft: 'auto',
    marginRight: 'auto',
    color: '#14213D',
    borderColor: '#FCA311',
    borderWidth: 1,
    borderRadius: 9,
  },
  chronoIconShow: {
    color: '#fca311',
  },
  statusView: {
    display: 'flex',
    flexDirection: 'row',
    paddingTop: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  statusBarImage: {
    width: 30,
    height: 30,
    alignItems: 'center',
    marginTop: 5,
    bottom: 5,
  },
  statusBarText: {
    width: '50%',
    textAlign: 'center',
    alignItems: 'center',
    marginVertical: 5,
    color: '#fca311',
  },
  statusBarDay: {
    width: '100%',
    height: 30,
    marginHorizontal: 10,
    alignItems: 'center',
    color: '#14213D',
    textAlign: 'center',
  },
  chronoItemButton: {
    width: '100%',
    height: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  dayButton: {
    width: '80%',
    textAlign: 'center',
    color: 'white',
    borderColor: 'white',
    borderRadius: 9,
    borderWidth: 2,
    marginLeft: 'auto',
    marginRight: 'auto',
    marginVertical: 5,
  },
  secondaryMenuButton: {
    right: 30,
    bottom: 30,
    backgroundColor: '#14213D',
    borderRadius: 9,
    position: 'absolute',
  },
  none: {
    display: 'none',
  },
  messageContainer: {
    width: '80%',
    backgroundColor: '#14213D',
    marginTop: 10,
    marginLeft: 'auto',
    marginRight: 'auto',
    borderRadius: 9,
  },
  message: {
    color: 'white',
    textAlign: 'center',
  },
  testmsg: {
    color: '#14213D',
    textAlign: 'center',
  },
}))
